build:
  frontend:
    image: birkhofflee/coffeeforever:node-0.10
    commands:
      - pwd
      - npm install
      - coffee --compile -o lib/ src/
      - cp lib/config.sample.js lib/config.js
      - npm test
  backend:
    image: dflemstr/drone-dind
    privileged: true
    script:
      - docker build .
notify:
  email:
    from: drone@birkhoff.me
    host: smtp.gmail.com
    username: $$GMAIL_USERNAME
    password: $$GMAIL_PASSWORD
    recipients:
      - admin@birkhoff.me
    subject: >
      [{{ build.status }}]
      {{ repo.owner }}/{{ repo.name }}
      ({{ build.branch }} - {{ truncate build.commit 8 }})
    template: >
      https://git.io/vgvPz