build:
  frontend:
    image: birkhofflee/coffeeforever:node-0.10
    commands:
      - npm install
      - cp -r src/ lib/
      - cd lib
      - coffee --compile .
      - cp config.sample.js config.js
      - npm test
notify:
  email:
    from: drone@birkhoff.me
    host: smtp.gmail.com
    username: $$GMAIL_USERNAME
    password: $$GMAIL_PASSWORD
    recipients:
      - admin@birkhoff.me
    subject: >
      [{{ build.status }}]
      {{ repo.owner }}/{{ repo.name }}
      ({{ build.branch }} - {{ truncate build.commit 8 }})
    template: >
      https://git.io/vgvPz
