build:
  frontend:
    image: birkhofflee/coffeeforever:node-0.10
    commands:
      - npm install
      - coffee --compile -o lib/ src/
      - cp lib/config.sample.js lib/config.js
      - npm test
  backend:
    image: docker:1.11.2
    commands:
      - cat
      - docker build . -t anonypages:test