// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    notFound: function(req, res) {
      res.status(404);
      return res.send("404 page not found: " + req.url);
    }
  };

}).call(this);
