// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function() {
    var e, error, langPath, result;
    global.AnonyPages.language = global.AnonyPages.config.lang != null ? global.AnonyPages.config.lang : "en-US";
    langPath = __dirname + "/../locale/" + global.AnonyPages.language + ".json";
    try {
      result = require(langPath);
    } catch (error) {
      e = error;
      new Error("Could not load the locale file which should located at " + langPath);
      false;
    }
    return result;
  };

}).call(this);
