// Generated by CoffeeScript 1.10.0
(function() {
  var Q, request;

  Q = require("q");

  request = require("request");

  module.exports = {
    verify: function(gResponse) {
      var config, deferred, url;
      deferred = Q.defer();
      config = global.AnonyPages.config.googleRecaptcha;
      url = config.verifyURL;
      request.post({
        url: config.verifyURL,
        encoding: null,
        gzip: true,
        form: {
          secret: config.siteSecret,
          response: gResponse
        },
        followRedirect: true
      }, function(error, response, body) {
        var e, error1, jsonResult;
        if (error) {
          console.log(error);
          deferred.reject("recaptcha!");
        }
        try {
          jsonResult = JSON.parse(body.toString());
        } catch (error1) {
          e = error1;
          deferred.reject("recaptcha!");
        }
        if (!jsonResult.success) {
          deferred.reject("recaptcha");
        }
        return deferred.resolve();
      });
      return deferred.promise;
    }
  };

}).call(this);
