// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    lang: "zh-TW",
    pages: {
      669071589906025: {
        pageName: "靠北AVA",
        hashtag: "#靠北AVA",
        pageUrl: "https://www.facebook.com/KaoBeiAVA/",
        afterPost: "發文請至 goo.gl/7slKsw 並遵守使用條款",
        postLabel: "靠北！都可以靠北！",
        postPlaceholder: "想靠北點什麼？",
        terms: "若您確認提交了本表單的內容，即表示您同意我們以下所列之使用條約。\n1. 管理員們每日縝密審查靠北貼文。如貼文內含有違反此條款之任何一項，管理員有權利依情況對貼文做出小幅度變更或選擇刪除該貼文而不做出任 何提醒。必要時，我們有權利直接封鎖您的 IP 位置及臉書賬號唯一辨識碼以阻止您使用此服務。 \n2. 您所提交之任何靠北內容完全不代表本粉絲專頁之觀點或立場。若有爭議，請私訊管理員。\n3. 您所提交之任何靠北內容不應違反中華民 國法律之規定。包括但不限於：人身攻擊、洩露個資、廣告文、政治文、尋仇文、超短文、宣傳文、連結文、釣魚文、重複文及無意義之文章等，若違反規定，均會在短時間內遭到移除。\n4. 您不應冒充管理員做出任何「偽」公告。\n5. 在文 章發佈後，我們不會依照使用者的單方面要求刪除任何貼文。如該貼文有爭議請立即私訊我們以維護您的權益。\n6. 若本條款的任何條款根據任何法律被整體或部分視為非法、無效或不可強制執行，此條款或相關部份應被視為不屬於本條款，本 條款的餘下條文的合法性、有效性及可強制執行性應不受影響。\n7. 管理人員有權利在任何時間更改此條約而不做出任何公告。\n8. 本臉書專頁、網站及管理者保有一切最終解釋權利。",
        access_token: "CAAYJN4aj1KUBALD7KbbhLTcN8lBSIJWtglsUaVN1E5zE2trPYDpncCJ3eRBKsBAVf8Y3yM2tJk18p4Rck1ttAtAA6sBqcRCKrv9deuzRlMecZBAhxRWlCWZCXAnNmeqlUiUJjUZAV86ectQBxTv4tHYVRhO39QgbRi5eQZBqoHLZAUo7ZBFkHzQ MrXemdJlu9p1xHub22V8wZDZD"
      }
    },
    server: {
      port: 1826
    },
    googleRecaptcha: {
      siteKey: "6LeVoBITAAAAAMkGiC0tEdIMeq0Jg19ViOC9U2wI",
      siteSecret: "6LeVoBITAAAAAAjlGf2o3FzGuyY5EKJGZiIQjp12",
      verifyURL: "https://www.google.com/recaptcha/api/siteverify"
    },
    facebook: {
      app_id: "1698983946998949",
      app_secret: "4a8180a7ae65214e48845b7359016463",
      postURL: "https://www.facebook.com/{page_id}/posts/{postID}",
      hashtagURL: "https://www.facebook.com/hashtag/{hashtag}?story_id={postID}",
      getFeedURL: "https://graph.facebook.com/{pageID}/posts?access_token={accessToken}",
      postArticleURL: "https://graph.facebook.com/v2.5/{pageID}/feed",
      verifyUserAccessTokenURL: "https://graph.facebook.com/me/?access_token={accessToken}"
    },
    encryptKey: "i2j9c2ueUX9PO1QWwpofkas"
  };

}).call(this);
