// Generated by CoffeeScript 1.10.0
(function() {
  var crypto;

  crypto = require("crypto");

  global.AnonyPages.app.get('/decrypt/:key/:string', function(req, res) {
    var config, decipher, decoded;
    config = global.AnonyPages.config;
    if ((req.params.key == null) || !req.params.string || req.params.key !== config.encryptKey) {
      false;
    }
    decipher = crypto.createDecipher('aes-256-cbc', config.encryptKey.toString('binary'));
    decoded = decipher.update(req.params.string, 'hex', 'utf8');
    decoded += decipher.final('utf8');
    return res.redirect("https://www.facebook.com/app_scoped_user_id/" + decoded);
  });

}).call(this);
