// Generated by CoffeeScript 1.10.0
(function() {
  global.AnonyPages.app.get('/page/:pageID', function(req, res) {
    var config, pageConfig, pageID;
    if ((req.params.pageID == null) || typeof global.AnonyPages.config.pages[req.params.pageID] === "undefined") {
      global.AnonyPages.functions.notFound(req, res);
      return false;
    }
    config = global.AnonyPages.config;
    pageID = req.params.pageID;
    pageConfig = config.pages[pageID];
    return res.render("postForm", {
      gRsitekey: config.googleRecaptcha.siteKey,
      postPlaceholder: pageConfig.postPlaceholder,
      i18n: global.AnonyPages.i18n,
      postLabel: pageConfig.postLabel,
      pageName: pageConfig.pageName,
      Terms: pageConfig.terms,
      pageID: pageID,
      fb_app_id: config.facebook.app_id
    });
  });

}).call(this);
